### ISSUE TITLE
File Format parsing was already implemented in XLEngine

### ISSUE THREAD

**Issue by neuromancer** [AzazelN28/darkforces#5]
I noticed that you are looking for references on how to parse certain file formats from Dark Forces. The XLEngine already parse them here: 

https://github.com/Mindwerks/XLEngine/tree/master/fileformats

so perhaps that C functions could be useful for you.

**Comment by AzazelN28** [comment]
Thanks @neuromancer, I've been digging through that files and found some interesting things, like parsing LFDs but unfortunately FME and BM parsing are missing.
